project_id = "mbmmfgivhqzhjyneyelu"

[functions.bulk-create-users]
verify_jwt = false

[functions.send-contact-message]
verify_jwt = false

[functions.generate-illustration]
verify_jwt = true

[functions.batch-generate-illustrations]
verify_jwt = false

[functions.draft-item-from-image]
verify_jwt = true

[functions.get-app-icon]
verify_jwt = false